config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "events#index"

  resources :events

  post '/events/register', to: 'events#register_toggle', as: 'event_register_toggle'
  get '/events/:id/attendees', to: 'events#attendees', as: 'event_attendees'
  
  get '/users/:id/events', to: 'events#user_events', as: 'user_events'
  get '/users/attending-events', to: 'events#attending_events', as: 'user_attending_events'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :description, :location, :ticket_price, presence: true
  validates :ticket_price, inclusion: 0..500

  belongs_to :organizer, class_name: 'User'

  has_many :tickets, dependent: :destroy
  has_many :attendees, through: :tickets

  default_scope { order(:date) }
  scope :upcoming, -> { where(date: nil).or(where('date > ?', Time.now)) }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
    
  validates :username, presence: true

  has_many :tickets, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :tickets, source: :event
  has_many :organized_events, foreign_key: :organizer_id, class_name: 'Event', dependent: :destroy

  default_scope { order(:username) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy register_toggle attending_events]

  def index
    @search_query = params[:q]
    
    if @search_query
      @events = Event.upcoming.where("LOWER(name) LIKE ?", "%" + Event.sanitize_sql_like(@search_query.downcase) + '%')
    else
      @events = Event.upcoming
    end
  end

  def show
    @event = Event.find_by(id: params[:id])

    if @event.nil?
      flash[:alert] = 'Event not found.'
      return redirect_to root_path
    end

    @event_ended = @event.date && Time.now > @event.date
  end

  def new
    @event = Event.new
  end

  def create
    event_hash = params.dig(:event)
    @event = current_user.organized_events.new(name: event_hash.dig(:name), location: event_hash.dig(:location),
                                               ticket_price: event_hash.dig(:ticket_price), date: event_hash.dig(:date),
                                               description: event_hash.dig(:description))

    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find_by(id: params[:id])

    if @event.nil?
      flash[:alert] = 'Event not found.'
      redirect_to root_path
    elsif current_user != @event.organizer
      flash[:alert] = 'You do not have permissions to edit this event.'
      redirect_to root_path
    elsif @event.date && Time.now > @event.date
      flash[:alert] = 'Event has already ended.'
      redirect_to event_path(@event)
    end
  end

  def update
    @event = Event.find_by(id: params[:id])
    event_hash = params.dig(:event)

    if @event.nil?
      flash[:alert] = 'Event not found.'
      return redirect_to root_path
    elsif current_user != @event.organizer
      flash[:alert] = 'You do not have permissions to edit this event.'
      return redirect_to root_path
    elsif @event.date && Time.now > @event.date
      flash[:alert] = 'Event has already ended.'
      return redirect_to event_path(@event)
    end

    if @event.update(name: event_hash.dig(:name), location: event_hash.dig(:location), ticket_price: event_hash.dig(:ticket_price),
                     date: event_hash.dig(:date), description: event_hash.dig(:description))
      redirect_to event_path(@event)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    event = Event.find_by(id: params[:id])

    if event.nil?
      flash[:alert] = 'Event does not exist.'
      return redirect_to root_path
    end

    if current_user == event.organizer
      event.destroy
      flash[:notice] = 'Event has been deleted.'
      redirect_to root_path
    else
      flash[:alert] = 'You do not have permissions to delete this event.'
      redirect_to root_path
    end
  end

  def register_toggle
    event = Event.find_by(id: params.dig(:id))

    if event.nil?
      flash[:alert] = 'Event not found.'
      return redirect_to root_path
    elsif event.organizer == current_user
      flash[:alert] = "You can't register for your own event."
      return redirect_to event_path(event)
    end

    if event.date && Time.now > event.date
      flash[:alert] = 'Event has already taken place.'
      return redirect_to event_path(event)
    end

    if event.attendees.exists?(current_user.id)
      event.attendees.delete(current_user)
      flash[:notice] = 'Unregistered from an event.'
    else
      event.attendees << current_user
      flash[:notice] = 'Successfully registered for an event.'
    end

    redirect_to event_path(event)
  end

  def attendees
    @event = Event.find_by(id: params[:id])

    if @event.nil?
      flash[:alert] = 'Event not found.'
      return redirect_to root_path
    elsif @event.organizer != current_user
      flash[:alert] = 'You do not have permissions to access this page.'
      return redirect_to event_path(@event)
    end

    @event_ended = @event.date && Time.now > @event.date 
  end

  def user_events
    @user = User.find_by(id: params[:id])

    if @user.nil?
      flash['alert'] = 'User does not exist.'
      return redirect_to root_path
    end

    @events = @user.organized_events
  end

  def attending_events
    @events = current_user.attended_events
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :username])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_list.html.erb
<div class="page-wrapper">
    <h2 style="font-size: 3em; margin: 0;"><%= heading %></h2>

    <% if events.any? %>
        <ul class="list">
            <% events.each do |event| %>
                <li>
                    <a href="<%= event_path(event) %>" style="<% if event.date && Time.now > event.date %>color: rgb(111, 114, 135);<% end %>"><%= event.name %></a>
                    <% if event.date %>
                        <span style="font-size: 0.6em; color: rgb(111, 114, 135);"> (<%= event.date&.strftime('%b %d') %>)</span>
                    <% end %>
                </li>
            <% end %>
        </ul>
    <% else %>
        <p class="empty-list-msg"><%= empty_list_msg %></p>
    <% end %>
</div>

app/views/events/_form.html.erb
<% if event.errors.any? %>
    <div class="form-errors">
        <p><%= pluralize(event.errors.count, 'error') %> prohibited this event from being saved:</p>

        <ul>
            <% event.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
    </div>
<% end%>

<div class="new-event-form-wrapper">
    <%= form_with model: event do |form| %>
        <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name, placeholder: 'The coolest event on Earth' %>
        </div>

        <div class="field">
            <%= form.label :description %>
            <%= form.text_area :description, placeholder: 'Attending our event will absolutely change your life!' %>
        </div>

        <div class="field">
            <%= form.label :location %>
            <%= form.text_field :location, placeholder: 'Fancy location' %>
        </div>

        <div class="field">
            <%= form.label :date %>
            <%= form.datetime_field :date %>
        </div>

        <div class="field">
            <%= form.label :ticket_price %>
            <%= form.number_field :ticket_price, min: '0', max: '500' %>
        </div>

        <%= form.submit %>
    <% end %>
</div>

app/views/events/attendees.html.erb
<div class="page-wrapper">
    <div class="flex-container">
        <div class="event-title-wrapper flex-item">
            <p><%= @event.date&.strftime('%b %d') %></p>
            <h2 class="event-title"><%= @event.name %></h2>
        </div><br/>

        <div class="flex-item flex-container">
            <div class="event-register-wrapper">
                <p class="event-info"><%=@event.ticket_price == 0 ? 'Free' : "#{@event.ticket_price}$"%></p>

                <%= link_to 'Event details', event_path(@event), class: @event_ended ? 'event-ended-details-btn' : 'event-register-btn' %>
            </div>
        </div>
    </div>

    <p style="color: rgb(111, 114, 135); font-size: 0.9em;">Earnings:
        <span class="bold"><%= @event.ticket_price * @event.attendees.count %>$</span>
    </p>

    <h3><% if @event_ended %>Event was attended by:<% else %>Event attendants<% end %></h3>
    <% if @event.attendees.any? %>
        <ul class="list">
            <% @event.attendees.each do |attendee| %>
                <li><%= link_to attendee.username, user_events_path(attendee) %></li>
            <% end %>
        </ul>
    <% else %>
        <p class="empty-list-msg">
            <% if @event_ended %>Event had no attendants.<% else %>Event has no attendants yet.<% end %>
        </p>
    <% end %>
</div>

app/views/events/attending_events.html.erb
<%= render 'events_list',
            heading: "Events I'm attending",
            events: @events,
            empty_list_msg: "You aren't registered to any events."
%>

app/views/events/edit.html.erb
<div class="page-wrapper">
    <h2 class="page-heading">Update Event</h2>

    <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<% if @events.empty? %>
    <p class="empty-list-msg" style="margin-left: 16px;">No events found</p>
<% else %>
    <div class="event-cards-container">
        <% @events.each do |event| %>
            <div class="event">
                <div class="event-card">
                    <img src="https://picsum.photos/400/200" alt="placeholder image">

                    <div class="event-card-info">
                        <%= link_to event.name, event_path(event), class: 'event-card-title' %>

                        <% if event.date %>
                            <p class="event-card-date"><%= event.date.strftime('%a, %b %e, %Y %l:%M %p') %></p>
                        <% else %>
                            <p class="event-card-date">Unknown date and time</p>
                        <% end %>

                        <p style="font-size: 0.8em; color: rgb(69,66,89);">Organized by
                        <span class="bold"><%= event.organizer.username %></span></p>

                        <div class="flex-container" style="align-items: center; font-size: 0.7em;">
                            <%= render 'shared/account_icon' %>
                            <%= event.attendees.count %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/events/new.html.erb
<div class="page-wrapper">
    <h2 class="page-heading">Organize Event</h2>

    <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="event-image-wrapper">
    <img class="event-image" src="https://picsum.photos/600/300" alt="event image">
</div>

<div class="event-detail">
    <div class="flex-container">
        <div class="flex-item">
            <div class="event-title-wrapper">
                <p><%= @event.date&.strftime('%b %d') %></p>
                <h2 class="event-title"><%= @event.name %></h2>
            </div>
        </div>

        
        <div class="flex-item flex-container">
            <div class="event-register-wrapper">
                <% if @event_ended %>
                    <p class="event-info">Event ended</p>
                    
                    <%= link_to current_user == @event.organizer ? 'Details' : 'More events',
                                current_user == @event.organizer ? event_attendees_path(@event) : user_events_path(@event.organizer),
                                class: 'event-ended-details-btn' 
                    %>
                <% else %>
                    <p class="event-info"><%=@event.ticket_price == 0 ? 'Free' : "#{@event.ticket_price}$"%></p>
                    
                    <% if user_signed_in? && @event.organizer != current_user %>
                        <form action="<%= event_register_toggle_path %>" id="event-register-toggle-form" method="post">
                            <input type="hidden" name="id" value="<%= @event.id %>">
                        </form>

                        <input type="submit"
                            form="event-register-toggle-form"
                            value="<% if @event.attendees.exists?(current_user.id) %>Unregister<% else %>Register<% end %>"
                            class="event-register-btn"
                        >
                    <% elsif !user_signed_in? %>
                        <%= link_to 'Sign in to register', new_user_session_path, class: 'event-register-btn' %>
                    <% elsif @event.organizer == current_user %>
                        <%= link_to 'See all attendees', event_attendees_path(@event), class: 'event-register-btn' %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>

    <p>Organized by <a href="<%= user_events_path(@event.organizer) %>"><%= @event.organizer.username %></a></p>

    <div class="flex-container" style="align-items: center;">
        <%= render 'shared/account_icon' %>
        <%= @event.attendees.count %>
    </div><br/>

    <div class="event-date-location-container">
        <h3>When and where</h3>

        <div class="flex-container" style="column-gap: 32px;">
            <div class="event-date-time-info-wrapper">
                <div class="event-date-time-icon-wrapper"><%= render 'shared/calendar_icon' %></div>

                <div>
                    <p class="event-date-time-header">Date and time</p>
                    <p class="event-date-time"><%= @event.date&.strftime('%a, %d %b %Y, %l:%M %p') || 'NOT SPECIFIED YET' %></p>
                </div>
            </div>
            
            <div class="event-location-info-wrapper">
                <div class="event-location-icon-wrapper"><%= render 'shared/map_marker_icon' %></div>

                <div>
                    <p class="event-location-header">Location</p>
                    <p class="event-location"><%= @event.location %></p>
                </div>
            </div>
        </div>
    </div><br/><br/>

    <div class="event-description-container">
        <h3>About this event</h3>

        <p class="event-description"><%= @event.description %></p>

        <% if current_user == @event.organizer %>
            <div class="event-actions">
                <%= link_to 'Delete', event_path(@event), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this event?' } %>

                <% unless @event.date && Time.now > @event.date %>
                    <%= link_to 'Update', edit_event_path(@event) %>
                <% end %>
            </div>
        <% end %>
    </div><br/><br/>
</div>

app/views/events/user_events.html.erb
<%= render 'events_list',
            heading: @user == current_user ? 'My events' : "#{@user.username}'s events",
            events: @events,
            empty_list_msg: @user == current_user ? "You aren't organizing any events" : "#{@user.username} isn't organizing any events." 
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventful</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shared/_account_icon.html.erb
<svg style="width:18px;height:18px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z" />
</svg>

app/views/shared/_calendar_icon.html.erb
<svg style="width:24px;height:24px" viewBox="0 0 24 24" >
    <path fill="currentColor" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1" />
</svg>

app/views/shared/_magnify.html.erb
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z" />
</svg>

app/views/shared/_magnify_icon.html.erb
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z" />
</svg>

app/views/shared/_map_marker.html.erb
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" />
</svg>

app/views/shared/_map_marker_icon.html.erb
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" />
</svg>

app/views/shared/_navbar.html.erb
<div class="navbar">
    <a class="main" href="<%= root_path %>">eventful</a>

    <div class="search-events-wrapper">
        <%= render 'shared/magnify_icon' %>
        <input id="search-event-input" type="search" placeholder="Search events">
    </div>

    <% if user_signed_in? %>
        <a href="<%= new_event_path %>">Organize</a>
        <a href="<%= edit_user_registration_path %>">Account</a>
        <a href="<%= destroy_user_session_path %>" style="margin-left: auto;" data-turbo-method="delete">Sign out</a>
    <% else %>
        <a href="<%= new_user_session_path %>" style="margin-left: auto;">Login</a>
        <a href="<%= new_user_registration_path %>">Register</a>
    <% end %>
</div>